#include "i2smicro.h"

i2s_chan_handle_t tx_handle;

//ONLY need TX since transmitting to audio amp
/*************************************************
Function Description:
    Initialize the i2s channel
Function Arguments:
    N/A
*************************************************/
void init_i2s_tx() {

    /* Get the default channel configuration by the helper macro.
    It can help to specify the I2S role and port ID */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

    /* Allocate a new TX channel and get the handle of this channel */
    i2s_new_channel(&chan_cfg, &tx_handle, NULL);

    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros are defined in 'i2s_std.h' which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(44100),
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_LRC, 
            .bclk = I2S_BCLK, 
            .ws = I2S_GPIO_UNUSED, 
            .dout = I2S_DOUT,
            .din = I2S_DIN, 
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };

    /* Initialize i2s channel to standard mode*/
    i2s_channel_init_std_mode(tx_handle, &std_cfg);    

    /* If the configurations of slot or clock need to be updated,
    * stop the channel first and then update it */
    // i2s_channel_disable(tx_handle);
    // std_cfg.slot_cfg.slot_mode = I2S_SLOT_MODE_MONO; // Default is stereo
    // i2s_channel_reconfig_std_slot(tx_handle, &std_cfg.slot_cfg);
    // std_cfg.clk_cfg.sample_rate_hz = 96000;
    // i2s_channel_reconfig_std_clock(tx_handle, &std_cfg.clk_cfg);

    printf("Initialized I2S\n");

}

/*************************************************
Function Description:
    Destroy/disable the i2s channel
Function Arguments:
    N/A
*************************************************/
void destroy_i2s_tx(){

    /* Safety check - make sure channel is disabled */
    i2s_channel_disable(tx_handle);

    /* If the handle is not needed any more, delete it to release the channel resources */
    i2s_del_channel(tx_handle);
}

/// @brief ///////////////////////////////////////////////////////
/// @param fp 
/// @return 
esp_err_t play_wav(const char *fp)
{
  printf("Opening file\n");
  FILE *fh = fopen(fp, "rb");
  if (fh == NULL)
  {
    printf("Can't open file.\n");
    return ESP_ERR_INVALID_ARG;
  }

  // skip the header...
  printf("skip header\n");
  fseek(fh, 44, SEEK_SET);

  // create a writer buffer
  printf("Create a write buffer.\n");
  int16_t *buf = calloc(AUDIO_BUFFER, sizeof(int16_t));
  size_t bytes_read = 0;
  size_t bytes_written = 0;

  bytes_read = fread(buf, sizeof(int16_t), AUDIO_BUFFER, fh);

  printf("Enable channel.\n");
  if (i2s_channel_enable(tx_handle) != ESP_OK) {
    printf("Failed to enable I2S channel.\n");
  }

  printf("Playing file...\n");
  while (bytes_read > 0)
  {
    // write the buffer to the i2s
    i2s_channel_write(tx_handle, buf, bytes_read * sizeof(int16_t), &bytes_written, portMAX_DELAY);
    bytes_read = fread(buf, sizeof(int16_t), AUDIO_BUFFER, fh);

  }

  i2s_channel_disable(tx_handle);
  free(buf);

  printf("Finished playing file.\n");
  return ESP_OK;
}



/*************************************************
Function Description:
    Write via i2s
Function Arguments:
    src_buf = pointer of sent data buffer
    bytes_to_write = Max data buffer length
    bytes_written = Bytes number that actually be sent
    ticks_to_wait = Max block time (milliseconds)
*************************************************/
void write_i2s_tx(i2s_chan_handle_t* tx_handle, const void* src_buf, size_t bytes_to_write, size_t bytes_written, uint32_t ticks_to_wait){
    
    /* Before writing data, start the TX channel first */
    i2s_channel_enable(*tx_handle);

    i2s_channel_write(*tx_handle, src_buf, bytes_to_write, &bytes_written, ticks_to_wait);

    /* Have to stop the channel before deleting it */
    i2s_channel_disable(*tx_handle);
}