#include "i2smicro.h"

i2s_chan_handle_t tx_handle;

//ONLY need TX since transmitting to audio amp
/*************************************************
Function Description:
    Initialize the i2s channel
Function Arguments:
    N/A
*************************************************/
void init_i2s_tx() {

    /* Get the default channel configuration by the helper macro.
    It can help to specify the I2S role and port ID */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);

    /* Allocate a new TX channel and get the handle of this channel */
    i2s_new_channel(&chan_cfg, &tx_handle, NULL);

    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros are defined in 'i2s_std.h' which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(48000),
        .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED, //check
            .bclk = I2S_BCLK,
            .ws = GPIO_NUM_5, //check
            .dout = I2S_DOUT,
            .din = I2S_GPIO_UNUSED, //check
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };

    /* Initialize i2s channel to standard mode*/
    i2s_channel_init_std_mode(tx_handle, &std_cfg);    

    /* If the configurations of slot or clock need to be updated,
    * stop the channel first and then update it */
    // i2s_channel_disable(tx_handle);
    // std_cfg.slot_cfg.slot_mode = I2S_SLOT_MODE_MONO; // Default is stereo
    // i2s_channel_reconfig_std_slot(tx_handle, &std_cfg.slot_cfg);
    // std_cfg.clk_cfg.sample_rate_hz = 96000;
    // i2s_channel_reconfig_std_clock(tx_handle, &std_cfg.clk_cfg);

}

/*************************************************
Function Description:
    Destroy/disable the i2s channel
Function Arguments:
    N/A
*************************************************/
void destroy_i2s_tx(){

    /* Safety check - make sure channel is disabled */
    i2s_channel_disable(tx_handle);

    /* If the handle is not needed any more, delete it to release the channel resources */
    i2s_del_channel(tx_handle);
}

/*************************************************
Function Description:
    Write via i2s
Function Arguments:
    src_buf = pointer of sent data buffer
    bytes_to_write = Max data buffer length
    bytes_written = Bytes number that actually be sent
    ticks_to_wait = Max block time (milliseconds)
*************************************************/
void write_i2s_tx(const void* src_buf, size_t bytes_to_write, size_t bytes_written, uint32_t ticks_to_wait){
    
    /* Before writing data, start the TX channel first */
    i2s_channel_enable(tx_handle);

    i2s_channel_write(tx_handle, src_buf, bytes_to_write, bytes_written, ticks_to_wait);

    /* Have to stop the channel before deleting it */
    i2s_channel_disable(tx_handle);
}